declare namespace PageRoute {
  /**
   * the root route key
   * @translate 根路由
   */
  type RootRouteKey = 'root';

  /**
   * the not found route, which catch the invalid route path
   * @translate 未找到路由(捕获无效路径的路由)
   */
  type NotFoundRouteKey = 'not-found';

  /**
   * the route key
   * @translate 页面路由
   */
  type RouteKey =
    | '403'
    | '404'
    | '500'
    | 'constant-page'
    | 'login'
    | 'not-found'
    | 'about'
    | 'auth-demo'
    | 'auth-demo_permission'
    | 'auth-demo_super'
    | 'component'
    | 'component_button'
    | 'component_card'
    | 'component_table'
    | 'dashboard'
    | 'dashboard_analysis'
    | 'dashboard_workbench'
    | 'document'
    | 'document_naive'
    | 'document_project-link'
    | 'document_project'
    | 'document_vite'
    | 'document_vue'
    | 'exception'
    | 'exception_403'
    | 'exception_404'
    | 'exception_500'
    | 'function'
    | 'function_tab-detail'
    | 'function_tab-multi-detail'
    | 'function_tab'
    | 'function_websocket'
    | 'management'
    | 'management_auth'
    | 'management_role'
    | 'management_route'
    | 'management_user'
    | 'multi-menu'
    | 'multi-menu_first'
    | 'multi-menu_first_second-new'
    | 'multi-menu_first_second-new_third'
    | 'multi-menu_first_second'
    | 'plugin'
    | 'plugin_charts'
    | 'plugin_charts_antv'
    | 'plugin_charts_echarts'
    | 'plugin_copy'
    | 'plugin_editor'
    | 'plugin_editor_markdown'
    | 'plugin_editor_quill'
    | 'plugin_icon'
    | 'plugin_map'
    | 'plugin_print'
    | 'plugin_swiper'
    | 'plugin_video'
    | 'product_management_addproduct'
    | 'product_management_catelist'
    | 'product_depot_list'
    | 'product_depot_stock'
    | 'user_list'
    | 'user_rolelist'
    | 'user_allocated'
    | 'user_post'
    | 'user_add'
    | 'user_summary'
    | 'customer_list'
    | 'customer_level'
    | 'customer_tag'
    | 'customer_detail'
    | 'customer_group'
    | 'customer_order'
    | 'customer_consumption_buy'
    | 'customer_consumption_points'
    | 'quantify_quantify'
    | 'quantify_pre'
    | 'order_list'
    | 'order_delivery'
    | 'order_source'
    | 'performance_list'
    | 'performance_team'
    | 'performance_sale'
    | 'material_list'
    | 'invite_invitation'
    | 'invite_channel'
    | 'invite_position'
    | 'scheme_list'
    | 'team_list'
    | 'team_distribution'
    | 'funds_transaction'
    | 'funds_recharge'
    | 'system_builder_code'
    | 'system_builder_edit'
    | 'system_builder_category'
    | 'system_builder_maintenance'
    | 'system_builder_cache'
    | 'system_builder_cachelist'
    | 'system_delivery_shippingtemplate'
    | 'system_back_transactiontype'
    | 'system_back_recharge'
    | 'system_back_express'
    | 'system_notify_notice'
    | 'system_notify_inform'
    | 'system_web_webinfo'
    | 'system_web_record'
    | 'system_web_agreement'
    | 'system_log'
    | 'system_online'
    | 'menu_list'
    | 'workbench_index'
    | 'product_management_list';

  /**
   * last degree route key, which has the page file
   * @translate 最后一级路由(该级路有对应的页面文件)
   */
  type LastDegreeRouteKey = Extract<
    RouteKey,
    | '403'
    | '404'
    | '500'
    | 'constant-page'
    | 'login'
    | 'not-found'
    | 'about'
    | 'auth-demo_permission'
    | 'auth-demo_super'
    | 'component_button'
    | 'component_card'
    | 'component_table'
    | 'dashboard_analysis'
    | 'dashboard_workbench'
    | 'document_naive'
    | 'document_project-link'
    | 'document_project'
    | 'document_vite'
    | 'document_vue'
    | 'exception_403'
    | 'exception_404'
    | 'exception_500'
    | 'function_tab-detail'
    | 'function_tab-multi-detail'
    | 'function_tab'
    | 'function_websocket'
    | 'management_auth'
    | 'management_role'
    | 'management_route'
    | 'management_user'
    | 'multi-menu_first_second-new_third'
    | 'multi-menu_first_second'
    | 'plugin_charts_antv'
    | 'plugin_charts_echarts'
    | 'plugin_copy'
    | 'plugin_editor_markdown'
    | 'plugin_editor_quill'
    | 'plugin_icon'
    | 'plugin_map'
    | 'plugin_print'
    | 'plugin_swiper'
    | 'plugin_video'
    | 'product_management_addproduct'
    | 'product_management_catelist'
    | 'product_depot_list'
    | 'product_depot_stock'
    | 'user_list'
    | 'user_rolelist'
    | 'user_allocated'
    | 'user_post'
    | 'user_add'
    | 'user_summary'
    | 'customer_list'
    | 'customer_level'
    | 'customer_tag'
    | 'customer_detail'
    | 'customer_group'
    | 'customer_order'
    | 'customer_consumption_buy'
    | 'customer_consumption_points'
    | 'quantify_quantify'
    | 'quantify_pre'
    | 'order_list'
    | 'order_delivery'
    | 'order_source'
    | 'performance_list'
    | 'performance_team'
    | 'performance_sale'
    | 'material_list'
    | 'invite_invitation'
    | 'invite_channel'
    | 'invite_position'
    | 'scheme_list'
    | 'team_list'
    | 'team_distribution'
    | 'funds_transaction'
    | 'funds_recharge'
    | 'system_builder_code'
    | 'system_builder_edit'
    | 'system_builder_category'
    | 'system_builder_maintenance'
    | 'system_builder_cache'
    | 'system_builder_cachelist'
    | 'system_delivery_shippingtemplate'
    | 'system_back_transactiontype'
    | 'system_back_recharge'
    | 'system_back_express'
    | 'system_notify_notice'
    | 'system_notify_inform'
    | 'system_web_webinfo'
    | 'system_web_record'
    | 'system_web_agreement'
    | 'system_log'
    | 'system_online'
    | 'menu_list'
    | 'workbench_index'
    | 'product_management_list'
  >;
}
